In [13]:
import numpy as np
print("import completed")

import completed


### Day 1 task: Go through numpy practice questions
    source: https://machinelearningplus.com/python/101-numpy-exercises-python/#google_vignette

In [14]:
#Create a 1D array of numbers from 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#Create a 3×3 numpy array of all True values.
np.full([3,3], True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
#Extract all odd numbers from arr.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd = arr[arr % 2 == 1]
odd

array([1, 3, 5, 7, 9])

In [24]:
#Replace all odd numbers in arr with -1 without modifying the original arr.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd = np.where(arr % 2 == 1, -1, arr)
print(odd)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [25]:
# Convert the 1D array arr to a 2D array with 2 rows.
arr = np.arange(10)
arr.reshape([2,-1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])