In [2]:
import numpy as np
print("import completed")

import completed


### Day 1 task: Go through numpy practice questions
    source: https://machinelearningplus.com/python/101-numpy-exercises-python/#google_vignette

In [14]:
#Create a 1D array of numbers from 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#Create a 3×3 numpy array of all True values.
np.full([3,3], True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
#Extract all odd numbers from arr.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd = arr[arr % 2 == 1]
odd

array([1, 3, 5, 7, 9])

In [24]:
#Replace all odd numbers in arr with -1 without modifying the original arr.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd = np.where(arr % 2 == 1, -1, arr)
print(odd)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [25]:
# Convert the 1D array arr to a 2D array with 2 rows.
arr = np.arange(10)
arr.reshape([2,-1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
#Stack arrays a and b vertically and horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
vert = np.vstack([a, b])
hor = np.hstack([a, b])

print(f"vert stack = {vert}")
print(f"hor stack = {hor}")

vert stack = [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
hor stack = [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [8]:
#Using only numpy functions and the input array a, produce an array that first repeats 
#each element 3 times, then tiles the whole array 3 times.
a = np.array([1,2,3])
result = (np.repeat(a, 3), np.tile(a, 3))
result

(array([1, 1, 1, 2, 2, 2, 3, 3, 3]), array([1, 2, 3, 1, 2, 3, 1, 2, 3]))

In [9]:
#Find the common items between arrays a and b.
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

In [10]:
#From array a, remove all items that are present in array b.
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [11]:
#Get the positions (indices) where elements of a and b are equal.
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)


(array([1, 3, 5, 7]),)

In [13]:
#From array a, extract all items between 5 and 10 (inclusive).
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a<=10)]

array([ 6,  9, 10])

In [17]:
#Convert the scalar function maxx into a vectorized version that works element-wise on 
#arrays a and b.
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    
pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)


array([6., 7., 9., 8., 9., 7., 5.])

In [20]:
#Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
arr[:, [1, 0, 2]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [21]:
#Swap rows 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
arr[[1, 0, 2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [26]:
#Reverse the row and column order of the 2D array arr.
arr = np.arange(9).reshape(3,3)
row = arr[::-1]
col = arr[:,::-1]
print(row)
print(col)

[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [28]:
arr = np.random.uniform(5, 10, size=(5,3))
print(arr)

[[5.79671863 7.95641567 9.64266754]
 [8.35616151 5.78277677 5.61805913]
 [7.11436955 5.5379469  9.6141525 ]
 [5.24223365 6.17711762 7.36998753]
 [6.48633102 8.90101105 9.04740991]]
